# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- script: ls -la
  displayName: 'List files in the working directory'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Scarstack-IT-Training-Subscription (11eacc51-44b5-4174-9eeb-19f92f53ecc9)'
    subscriptionId: '11eacc51-44b5-4174-9eeb-19f92f53ecc9'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg-IaC-ARMPipelinesAzure'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: 'vNetARMTemplateDeploy.json'
    deploymentMode: 'Incremental'
