
name: Azure ARM with Cronitor Schedule

on:
  schedule:
    #- cron: '*/5 * * * *' # Schedules workflow to run every 5 minutes
    # - cron: '0 9 3 * *'   # Schedules workflow at 09:00 AM, on day 3 of the month
    # - cron: '45 10 * * WED'   # At 10:45 AM, only on Tuesday
    #- cron: '30 7 1 6 *'  # Schedules workflow to run on June 1, 7:30AM
    #- cron: '10 9 * * *'  # Schedules workflow to run same day at 9:10AM
  #workflow_dispatch:      # Deactivate this if you don't want a manual immediate execution included.

jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:
        # Checkout code
      - uses: actions/checkout@main

        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: rg-mktDp-eastus-prod-7yt56
          template: ./vNetARMTemplateDeploy.json

        # output containerName variable from template
      - run: echo ${{ steps.deploy.outputs.containerName }}
