
name: Azure ARM with Cronitor Schedule & Monitor

on:
  schedule:
    - cron: '*/5 * * * *' # use this if schedule is for the same day
    - cron: '32 8 2 7 *'
    - cron: '36 7 2 7 *'
  #workflow_dispatch: # Deactivate this if you don't want a manual immediate executrion included.

jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:
        # Checkout code
      - uses: actions/checkout@main

        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: rg-mktDp-eastus-prod-7yt56
          template: ./vNetARMTemplateDeploy.json

        # output containerName variable from template
      - run: echo ${{ steps.deploy.outputs.containerName }}
