name: Append data data every day at 00:10

on:
  push:
    branches:
      - main

  workflow_dispatch:
    # https://crontab.cronhub.io/
    # Run at 6:31 AM UTC on July 2, 2024
    # Run at 6:35 AM UTC on July 2, 2024
  schedule:
    - cron: '47 6 2 7 *'
    - cron: '49 6 2 7 *'

jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:

        # Checkout code
      - uses: actions/checkout@main

        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: rg-mktDp-eastus-prod-7yt56
          template: ./vNetARMTemplateDeploy.json

        # output containerName variable from template
      - run: echo ${{ steps.deploy.outputs.containerName }}
